<a href="https://colab.research.google.com/github/karlacastrokvcm/aqualimpia-dashboard/blob/main/analisis_aqualimpia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar librerías
import pandas as pd
import plotly.express as px

In [ ]:
# Cargar archivo
from google.colab import files
uploaded = files.upload()

Saving dataset_set_A_aguas_residuales.xlsx to dataset_set_A_aguas_residuales.xlsx

In [ ]:
# Leer dataset
df = pd.read_excel("dataset_set_A_aguas_residuales.xlsx")

In [ ]:
fig1 = px.bar(
    df.groupby("planta")["cumplimiento_norma"].mean().reset_index(),
    x="planta",
    y="cumplimiento_norma",
    title="Porcentaje de cumplimiento normativo por planta"
)

fig1.show()

In [ ]:
print(df.columns)

Index(['fecha_registro', 'planta', 'caudal_entrada_m3_d', 'DBO_entrada_mg_L',
       'SST_entrada_mg_L', 'pH_entrada', 'energia_aeracion_kWh',
       'lodos_generados_kg_d', 'DBO_salida_mg_L', 'cumplimiento_norma'],
      dtype='object')

In [ ]:
fig2 = px.line(
    df.sort_values("fecha_registro"),
    x="fecha_registro",
    y="DBO_salida_mg_L",
    color="planta",
    title="Evolución temporal de DBO de salida"
)

fig2.show()

In [ ]:
fig3 = px.scatter(
    df,
    x="caudal_entrada_m3_d",
    y="DBO_salida_mg_L",
    color="planta",
    size="energia_aeracion_kWh",
    title="Relación entre caudal y DBO de salida"
)

fig3.show()

In [ ]:
fig4 = px.box(
    df,
    x="planta",
    y="DBO_salida_mg_L",
    title="Distribución de DBO de salida por planta"
)

fig4.show()

In [ ]:
consumo = df.groupby("planta")["energia_aeracion_kWh"].mean().reset_index()

fig5 = px.bar(
    consumo,
    x="planta",
    y="energia_aeracion_kWh",
    title="Consumo promedio de energía en aireación"
)

fig5.show()

In [ ]:
fig6 = px.line(
    df.sort_values("fecha_registro"),
    x="fecha_registro",
    y="lodos_generados_kg_d",
    color="planta",
    title="Generación de lodos por planta"
)

fig6.show()

In [ ]:
df["eficiencia_DBO"] = (
    (df["DBO_entrada_mg_L"] - df["DBO_salida_mg_L"])
    / df["DBO_entrada_mg_L"]
) * 100

In [ ]:
fig7 = px.bar(
    df.groupby("planta")["eficiencia_DBO"].mean().reset_index(),
    x="planta",
    y="eficiencia_DBO",
    title="Eficiencia promedio de remoción de DBO"
)

fig7.show()

In [ ]:
# ================================
# PROYECTO AQUA LIMPIA S.A.
# Análisis exploratorio de plantas
# ================================

import pandas as pd
import plotly.express as px
from google.colab import files

# Cargar archivo
uploaded = files.upload()

# Leer dataset
df = pd.read_excel("dataset_set_A_aguas_residuales.xlsx")

# Revisar estructura
print(df.info())
display(df.head())

# Convertir fecha
df["fecha_registro"] = pd.to_datetime(df["fecha_registro"])

# Crear indicador de eficiencia de remoción de DBO
df["eficiencia_DBO_%"] = (
    (df["DBO_entrada_mg_L"] - df["DBO_salida_mg_L"]) /
    df["DBO_entrada_mg_L"]
) * 100

# Crear estado textual de cumplimiento
df["estado_cumplimiento"] = df["cumplimiento_norma"].map({
    1: "Cumple",
    0: "No cumple"
})

# Revisar datos finales
display(df.head())

Saving dataset_set_A_aguas_residuales.xlsx to dataset_set_A_aguas_residuales (2).xlsx
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fecha_registro        200 non-null    object
 1   planta                200 non-null    object
 2   caudal_entrada_m3_d   200 non-null    int64
 3   DBO_entrada_mg_L      200 non-null    int64
 4   SST_entrada_mg_L      200 non-null    int64
 5   pH_entrada            200 non-null    float64
 6   energia_aeracion_kWh  200 non-null    float64
 7   lodos_generados_kg_d  200 non-null    float64
 8   DBO_salida_mg_L       200 non-null    float64
 9   cumplimiento_norma    200 non-null    int64
dtypes: float64(4), int64(4), object(2)
memory usage: 15.8+ KB
None

,fecha_registro,planta,caudal_entrada_m3_d,DBO_entrada_mg_L,SST_entrada_mg_L,pH_entrada,energia_aeracion_kWh,lodos_generados_kg_d,DBO_salida_mg_L,cumplimiento_norma
0,2025-08-17,Planta Sur,6562,271,324,7.12,1261.1,440.3,40.0,0
1,2025-09-07,Planta Sur,5336,322,230,7.01,1629.3,561.2,26.8,1
2,2025-07-26,Planta Norte,5755,318,282,6.79,1469.2,441.6,45.2,0
3,2025-10-27,Planta Centro,6840,216,167,7.01,1764.8,560.0,38.0,0
4,2025-09-06,Planta Centro,6803,326,200,7.55,1409.3,654.0,32.1,0

,fecha_registro,planta,caudal_entrada_m3_d,DBO_entrada_mg_L,SST_entrada_mg_L,pH_entrada,energia_aeracion_kWh,lodos_generados_kg_d,DBO_salida_mg_L,cumplimiento_norma,eficiencia_DBO_%,estado_cumplimiento
0,2025-08-17,Planta Sur,6562,271,324,7.12,1261.1,440.3,40.0,0,85.239852,No cumple
1,2025-09-07,Planta Sur,5336,322,230,7.01,1629.3,561.2,26.8,1,91.677019,Cumple
2,2025-07-26,Planta Norte,5755,318,282,6.79,1469.2,441.6,45.2,0,85.786164,No cumple
3,2025-10-27,Planta Centro,6840,216,167,7.01,1764.8,560.0,38.0,0,82.407407,No cumple
4,2025-09-06,Planta Centro,6803,326,200,7.55,1409.3,654.0,32.1,0,90.153374,No cumple

In [ ]:
# Cumplimiento normativo por planta
cumplimiento = df.groupby("planta")["cumplimiento_norma"].mean().reset_index()

fig1 = px.bar(
    cumplimiento,
    x="planta",
    y="cumplimiento_norma",
    title="Porcentaje de cumplimiento normativo por planta",
    labels={
        "planta": "Planta",
        "cumplimiento_norma": "Cumplimiento promedio"
    }
)

fig1.show()

In [ ]:
# Evolución temporal de DBO de salida
fig2 = px.line(
    df.sort_values("fecha_registro"),
    x="fecha_registro",
    y="DBO_salida_mg_L",
    color="planta",
    title="Evolución temporal de DBO del efluente tratado",
    labels={
        "fecha_registro": "Fecha",
        "DBO_salida_mg_L": "DBO salida mg/L"
    }
)

fig2.show()

In [ ]:
# Relación entre caudal y DBO de salida
fig3 = px.scatter(
    df,
    x="caudal_entrada_m3_d",
    y="DBO_salida_mg_L",
    color="planta",
    size="energia_aeracion_kWh",
    hover_data=["fecha_registro", "cumplimiento_norma"],
    title="Relación entre caudal, energía de aireación y DBO de salida"
)

fig3.show()

In [ ]:
# Distribución de DBO de salida por planta
fig4 = px.box(
    df,
    x="planta",
    y="DBO_salida_mg_L",
    color="planta",
    title="Distribución de DBO de salida por planta"
)

fig4.show()

In [ ]:
# Eficiencia promedio de remoción de DBO
eficiencia = df.groupby("planta")["eficiencia_DBO_%"].mean().reset_index()

fig5 = px.bar(
    eficiencia,
    x="planta",
    y="eficiencia_DBO_%",
    title="Eficiencia promedio de remoción de DBO por planta"
)

fig5.show()

In [ ]:
# Archivo para Operaciones
operaciones = df[
    [
        "fecha_registro",
        "planta",
        "caudal_entrada_m3_d",
        "DBO_entrada_mg_L",
        "DBO_salida_mg_L",
        "energia_aeracion_kWh",
        "lodos_generados_kg_d",
        "eficiencia_DBO_%"
    ]
]

operaciones.to_excel("salida_area_operaciones.xlsx", index=False)
files.download("salida_area_operaciones.xlsx")

In [ ]:
# Archivo para Gestión Ambiental
gestion_ambiental = df[
    [
        "fecha_registro",
        "planta",
        "DBO_salida_mg_L",
        "cumplimiento_norma",
        "estado_cumplimiento"
    ]
]

gestion_ambiental.to_excel("salida_gestion_ambiental.xlsx", index=False)
files.download("salida_gestion_ambiental.xlsx")

# Proyecto de Análisis de Datos – AquaLimpia S. A.

## Descripción del Proyecto

AquaLimpia S. A. opera diversas plantas de tratamiento de aguas residuales urbanas e industriales. Durante el último trimestre se detectaron incumplimientos intermitentes en parámetros críticos de calidad del efluente tratado, especialmente en los niveles de DBO y eficiencia del tratamiento.

El proyecto de análisis de datos busca identificar patrones operacionales y ambientales que apoyen la toma de decisiones y el cumplimiento normativo.

---

# Objetivos

## Objetivo General

Analizar el desempeño de las plantas de tratamiento mediante técnicas de análisis exploratorio de datos y visualización, para apoyar decisiones operacionales y ambientales.

## Objetivos Específicos

- Identificar patrones de incumplimiento normativo.
- Comparar el desempeño entre plantas.
- Evaluar la eficiencia de remoción de DBO.
- Analizar la relación entre caudal, energía y calidad del efluente.
- Generar reportes para distintas áreas de la empresa.

---

# Herramientas Utilizadas

- Python
- Google Colab
- Pandas
- Plotly Express
- Git y GitHub

---

# Proceso Analítico

## 1. Carga de Datos

Se importó el dataset oficial en formato Excel utilizando Pandas.

```python
df = pd.read_excel("dataset_set_A_aguas_residuales.xlsx")
```

## 2. Preparación y Limpieza

Se realizaron tareas de:

- Conversión de fechas.
- Revisión de valores nulos.
- Validación de columnas.
- Creación de indicadores.

### Indicador de eficiencia

```python
df["eficiencia_DBO_%"] = (
    (df["DBO_entrada_mg_L"] - df["DBO_salida_mg_L"])
    / df["DBO_entrada_mg_L"]
) * 100
```

---

# Dashboard Exploratorio

Se desarrollaron visualizaciones para analizar:

- Cumplimiento normativo por planta.
- Evolución temporal de DBO.
- Relación entre caudal y DBO de salida.
- Consumo energético.
- Generación de lodos.
- Eficiencia del tratamiento.

---

# Resultados Obtenidos

El análisis permitió:

- Detectar plantas con menor cumplimiento normativo.
- Identificar variaciones en la calidad del efluente tratado.
- Observar relación entre altos caudales y aumento de DBO.
- Comparar eficiencia operacional entre plantas.
- Generar información útil para Operaciones y Gestión Ambiental.

---

# Archivos Generados

## Área de Operaciones

Incluye:

- Fecha de registro
- Planta
- Caudal de entrada
- DBO entrada y salida
- Energía de aireación
- Lodos generados
- Eficiencia del tratamiento

## Área de Gestión Ambiental

Incluye:

- Fecha de registro
- Planta
- DBO del efluente tratado
- Estado de cumplimiento normativo

---

# Reproducibilidad

El proyecto fue organizado en un repositorio GitHub con la siguiente estructura:

```text
aqualimpia-dashboard/
│
├── data/
├── notebooks/
├── outputs/
├── README.md
└── requirements.txt
```

Esto permite mantener trazabilidad, reutilizar scripts y actualizar el análisis con nuevos datos.

---

# Conclusión

El proyecto permitió transformar datos operacionales en información útil para apoyar la toma de decisiones en AquaLimpia S. A. El dashboard y los archivos generados facilitan el monitoreo del desempeño de las plantas y el cumplimiento de la normativa ambiental.

In [ ]:
# indicadores.py

def calcular_eficiencia(df):

    df["eficiencia_DBO_%"] = (
        (df["DBO_entrada_mg_L"] - df["DBO_salida_mg_L"])
        / df["DBO_entrada_mg_L"]
    ) * 100

    return df

In [ ]:
# visualizaciones.py

import plotly.express as px

def grafico_cumplimiento(df):

    resumen = (
        df.groupby("planta")["cumplimiento_norma"]
        .mean()
        .reset_index()
    )

    fig = px.bar(
        resumen,
        x="planta",
        y="cumplimiento_norma",
        title="Cumplimiento normativo por planta"
    )

    fig.show()

In [ ]:
# Revisar valores nulos
df.isnull().sum()

fecha_registro          0
planta                  0
caudal_entrada_m3_d     0
DBO_entrada_mg_L        0
SST_entrada_mg_L        0
pH_entrada              0
energia_aeracion_kWh    0
lodos_generados_kg_d    0
DBO_salida_mg_L         0
cumplimiento_norma      0
eficiencia_DBO_%        0
estado_cumplimiento     0
dtype: int64

In [ ]:
# Revisar registros duplicados
df.duplicated().sum()

np.int64(0)

In [ ]:
# Revisar tipos de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fecha_registro        200 non-null    datetime64[ns]
 1   planta                200 non-null    object
 2   caudal_entrada_m3_d   200 non-null    int64
 3   DBO_entrada_mg_L      200 non-null    int64
 4   SST_entrada_mg_L      200 non-null    int64
 5   pH_entrada            200 non-null    float64
 6   energia_aeracion_kWh  200 non-null    float64
 7   lodos_generados_kg_d  200 non-null    float64
 8   DBO_salida_mg_L       200 non-null    float64
 9   cumplimiento_norma    200 non-null    int64
 10  eficiencia_DBO_%      200 non-null    float64
 11  estado_cumplimiento   200 non-null    object
dtypes: datetime64[ns](1), float64(5), int64(4), object(2)
memory usage: 18.9+ KB

In [ ]:
# Estadísticas generales
df.describe()

,fecha_registro,caudal_entrada_m3_d,DBO_entrada_mg_L,SST_entrada_mg_L,pH_entrada,energia_aeracion_kWh,lodos_generados_kg_d,DBO_salida_mg_L,cumplimiento_norma,eficiencia_DBO_%
count,200,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.00000,200.000000
mean,2025-08-29 15:50:24,5059.285000,280.145000,232.670000,7.16240,1256.394500,428.795500,36.177500,0.22500,87.092908
min,2025-07-01 00:00:00,1500.000000,90.000000,70.000000,6.18000,279.700000,113.700000,10.200000,0.00000,80.692308
25%,2025-07-31 00:00:00,4193.750000,223.000000,192.500000,6.84750,950.650000,321.175000,26.075000,0.00000,84.754466
50%,2025-08-30 12:00:00,5092.500000,284.000000,233.500000,7.14000,1212.850000,429.700000,35.150000,0.00000,86.999935
75%,2025-09-29 06:00:00,6037.750000,333.250000,277.500000,7.45250,1516.750000,524.825000,45.825000,0.00000,89.679486
max,2025-10-28 00:00:00,9205.000000,481.000000,391.000000,8.27000,2434.000000,971.700000,79.000000,1.00000,93.431953
std,NaN,1410.971334,75.566497,64.289398,0.42381,420.146335,144.744253,13.259427,0.41863,3.099086

In [ ]:
df[df["DBO_salida_mg_L"] > df["DBO_entrada_mg_L"]]

Empty DataFrame
Columns: [fecha_registro, planta, caudal_entrada_m3_d, DBO_entrada_mg_L, SST_entrada_mg_L, pH_entrada, energia_aeracion_kWh, lodos_generados_kg_d, DBO_salida_mg_L, cumplimiento_norma, eficiencia_DBO_%, estado_cumplimiento]
Index: []

In [1]:
import shutil

shutil.make_archive(
    "aqualimpia_proyecto",
    "zip",
    "/content"
)

'/content/aqualimpia_proyecto.zip'

In [2]:
from google.colab import files
files.download("aqualimpia_proyecto.zip")